version: '3'

services:
  wg-easy:
    image: weejewel/wg-easy
    container_name: WG-GUI
    restart: unless-stopped
    ports:
      - "51000:51820/udp"
      - "80:51821/tcp"
    volumes:
      - ~/.wg-easy:/etc/wireguard
    environment:
      - WG_HOST=34.101.161.27
      - PASSWORD=[password-disesuaikan]
      - WG_PORT=51000
      - WG_MTU=1420
      - WG_PERSISTENT_KEEPALIVE=25
      - WG_DEFAULT_ADDRESS=10.0.0.x
      - WG_DEFAULT_DNS=8.8.8.8
      - WG_ALLOWED_IPS=0.0.0.0/0
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
